### ISSUE TITLE
Cross-site cookies

### ISSUE THREAD

**Issue by terodelarosa** [Automattic/vip-decoupled-bundle#35]
Hello, we're trying to get the project up and running with a Next.js app with login functionality.

In local development we've already configured the subsite "http://manage.3000.vipdev.lndo.site/" to point its home to "http://localhost:3000" where our Nextjs app is located, and this results in a "301 Moved Permanently" which forces navigation to localhost.

However after login via GraphQL mutation we get a "Set-Cookie" response header which is ignored because it references a different domain ".3000.vipdev.lndo.site".

So the question would be how do we redirect a subsite to the Nextjs app without losing the domain in the URL.
Thank you in advance.

<img width="965" alt="Screenshot 2021-11-29 at 10 34 59" src="https://user-images.githubusercontent.com/2419480/143843158-b9771897-5b1f-40af-af73-1fd252ccc05d.png">

**Comment by chriszarate** [comment]
Hi @terodelarosa! This issue might be better suited to the plugin that is providing the login mutation.

However, it looks to me like that `Set-Cookie` was not blocked because the origins didn't match. Instead, it was blocked because of the `SameSite=Lax` attribute. In production, you will need to adjust the `Set-Cookie` response header to provide `SameSite=None;Secure=true`. In development, since you usually cannot implement HTTPS on your development domains, you will need to return `SameSite=false`.

This SO post might be helpful:
https://stackoverflow.com/questions/63010545/issue-with-cross-site-cookies-how-to-set-cookie-from-backend-to-frontend

**Comment by chriszarate** [comment]
Closing, but feel free to reopen if the issue points back to this plugin.
